# Common settings for all boards

esphome:
  name: ${name}
  comment: "PiggyMeter IEC62056-21"

esp32:
  variant: ${variant}
  board: ${board}
  framework:
    type: esp-idf

logger:
  level: DEBUG
  # level: INFO

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_pass
  # Optional domain
  # domain: .lan

#api:
#  encryption:
#    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_pass

web_server:
  port: 80

prometheus:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

external_components:
    # IEC62056-21 component
  - source: github://pcmihnea/esphome-iec62056

uart:
  - id: uart_meter
    rx_pin: ${rx_pin}
    tx_pin: ${tx_pin}
    baud_rate: 300
    data_bits: 7
    parity: EVEN
    stop_bits: 1

switch:
  - platform: gpio
    pin: ${led_pin}
    name: Internal LED
    id: led_switch
    internal: True

  - platform: iec62056
    name: 'Readout Trigger'
    id: 'readout_trigger'

binary_sensor:
  - platform: iec62056
    id: meter_status
    name: Meter Connection Status
    on_press:
      then:
        - switch.turn_on: led_switch
    on_release:
      then:
        - switch.turn_off: led_switch


iec62056:
  update_interval: 60s
  baud_rate_max: 9600

# Modify the list and OBIS codes if needed
# Doc:  https://aquaticus.info/iec62056.html

sensor:
  - platform: iec62056
    obis: 0.0.0
    name: Serial number
    state_class: measurement

  - platform: iec62056
    obis: 0.8.0
    name: Demand period
    device_class: duration
    state_class: measurement

#  - platform: iec62056
#    obis: 0.9.1
#    name: Current time
#    device_class: timestamp
#    state_class: measurement

#  - platform: iec62056
#    obis: 0.9.2
#    name: Current date
#    device_class: date
#    state_class: measurement

  - platform: iec62056
    obis: 0.9.5
    name: Day of the week
    state_class: measurement

  - platform: iec62056
    obis: 1.8.0
    name: Absolute active energy total
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: iec62056
    obis: 1.8.1
    name: Absolute active energy tariff 1
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: iec62056
    obis: 1.8.2
    name: Absolute active energy tariff 2
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: iec62056
    obis: 1.8.0*1
    name: Absolute active energy total, period 1
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: iec62056
    obis: 1.8.1*1
    name: Absolute active energy tariff 1, period 1
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: iec62056
    obis: 1.8.2*1
    name: Absolute active energy tariff 2, period 1
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: iec62056
    obis: 1.8.0*2
    name: Absolute active energy total, period 2
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: iec62056
    obis: 1.8.1*2
    name: Absolute active energy tariff 1, period 2
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: iec62056
    obis: 1.8.2*2
    name: Absolute active energy tariff 2, period 2
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

  - platform: iec62056
    name: Max demand
    obis: 1.6.0
    unit_of_measurement: kW
    accuracy_decimals: 3
    device_class: power
    state_class: total

  - platform: iec62056
    name: Max demand, period 1
    obis: 1.6.0*1
    unit_of_measurement: kW
    accuracy_decimals: 3
    device_class: power
    state_class: total

  - platform: iec62056
    name: Max demand, period 2
    obis: 1.6.0*2
    unit_of_measurement: kW
    accuracy_decimals: 3
    device_class: power
    state_class: total

  - platform: iec62056
    name: Instantaneous current
    obis: 31.7.0
    unit_of_measurement: A
    accuracy_decimals: 2
    device_class: current
    state_class: measurement

  - platform: iec62056
    name: Instantaneous voltage
    obis: 32.7.0
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement

# vendor-specific start
#  - platform: iec62056
#    obis: '96.71'
#    name: Current period start
#    device_class: date
#    state_class: measurement

#  - platform: iec62056
#    obis: 96.71*1
#    name: Period 1 start
#    device_class: date
#    state_class: measurement

#  - platform: iec62056
#    obis: 96.71*2
#    name: Period 2 start
#    device_class: date
#    state_class: measurement
